### ISSUE TITLE
Modification in View

### ISSUE THREAD

**Issue by ayush18verma** [qapqap/TimelineView#3]
If i don't want to put date, and want to put dynamic Title and description. How comes will get into it?
If i delete the method of date, it showing error. Please fix it soon and modify it.

Thanks.

**Comment by qapqap** [comment]
Try to replace the date with null, and make sure to pass false on arrange by date

`//Create the Timeline Adapter
ArrayAdapter<TimelineRow> myAdapter = new TimelineViewAdapter(this, 0, TimelineRowsList,
//if true, list will be arranged by date
                **false**);`

**Comment by ayush18verma** [comment]
Thanks.
