### ISSUE TITLE
About text color...

### ISSUE THREAD

**Issue by magdy-zon** [qapqap/TimelineView#9]
Hi my friend!
Thanks to you....
When I'm trying to implement the TimelineView the text color always is white.
I only want to ask you... How can I customize the text color of Listview?

**Comment by qapqap** [comment]
Hello,
Please use the new version v1.6.
To add the color to the text use:
``` xml
//to set row Date text color (optional)
myRow.setDateColor(Color.argb(255, 0, 0, 0));
// To set row Title text color (optional)
myRow.setTitleColor(Color.argb(255, 0, 0, 0));
// To set row Description text color (optional)
myRow.setDescriptionColor(Color.argb(255, 0, 0, 0));
```

**Comment by magdy-zon** [comment]
I appreciate your response, the library is helping me a lot.

Regards coder!
